Arquillian Warp Documentation
=============================
Lukas Fryc <lfryc@redhat.com>
:toc:

== What is Warp?

Arquillian Warp fills the void between client-side and server-side testing.

Arquillianはワープは、クライアント側とサーバー側のテストの間の空隙を埋める。

Using Warp, you can initiate an HTTP request using a client-side testing tool such as WebDriver and, in the same request cycle, execute in-container server-side tests. This powerful combination lets you cover integration across client and server.

The Warp effectively removes a need for mocking and opens new possibilities for debugging.

Warpは効果的にモック作成の必要性を削除し、デバッグのために新たな可能性を開きます。

== Where to Use Warp?

Warp allows you to know as little or as much of the application under test as you want.

=== Gray-box Testing

Initially, Warp can be used from any black-box testing tool (like HttpClient, REST client, Selenium WebDriver, etc.). But it allows to hook into server request lifecycle and verify what happens inside the box (referred to as white-box testing). That is why we identify Warp as gray-box testing framework.

まず、Warpは、あらゆるブラックボックステストツール（HttpClient、RESTクライアント、Selenium WebDriverを、等）から使用することができます。しかし、それはサーバ要求のライフサイクルにフックと（ホワイトボックステストとも呼ばれる）箱の中に何が起こるか確認することができます。我々はグレーボックステストフレームワークとしてワープを識別する理由です。

=== Integration Testing

On a scale of granularity of a test, Warp fits the best integration level of testing with a overlap to functional testing. You can either test components, application API or functional behavior.

=== Technology Independence

No matter of client-side tool you use for emiting HTTP request or what server-side framework runs on a server, Warp allows you to assert and verify logic on a most appropriate place of client-server request lifecycle.

=== Use Cases

Using Warp is limited just by your imagination, as long as you have in mind facts we had described earlier.

Just to note some specific use cases, Warp can:

* send a payload to a server
* verify an incoming request
* assert a state of a server context
* verify that given event was fired during request processing
* verify a completed response
* send a payload to a client

=== Deploying Warp

The Warp is good fit for basically any stage of a project:

* prototyping (TDD)
* legacy projects
* issue reproduction
* debugging issue

Thanks to an ability to bring an arbitrary payload to a server and hook into server-lifecycle, we can use Warp in partially implemented projects. We needn't to have database layer implemented in order to test UI logic. This is especially useful for projects based on loosely coupled components (e.g. Java EE's CDI).

Since we can use Warp and start with white-box testing, we can reproduce the issue on the level of application's interface (issue reproduction). Then we can dive deeper into internals of an application, which will not only allow us to reveal how it works, but also debug a system and assert a correct behavior.

=== Supported Tools and Frameworks

==== Cross-protocol

Warp currently supports only HTTP protocol, but conceptually it can be used with any protocol where we are able to intercept client-to-server communication on both, the client and the server.

==== Client-Side Testing Tools

Warp supports any client-side tools if you are using them in a way that requests can be intercepted (in a case of HTTP protocol, you need to communicate through a proxy instead of direct communication with a server).

The samples of such tools:

* `URL#getResourceAsStream()`
* Apache HTTP Client
* Selenium WebDriver

Note: in order to use Warp, you should inject an `@ArquillianResource` URL, which points to the proxy automatically.

==== Frameworks

Warp currently focuses on frameworks based on Servlets API, but it provides special hooks and additional support for:

* JSF
* JAX-RS (REST)
* Spring MVC

== How to Use Warp?

=== Project Setup

==== Setting Up Maven Dependencies

Following dependencies needs to be configured: Warp depchain (does contain support just for Servlets API)

----
<dependency>
    <groupId>org.jboss.arquillian.extension</groupId>
    <artifactId>arquillian-warp</artifactId>
    <version>${version.warp}</version>
    <type>pom</type>
</dependency>
----

or JSF-specific binding:

----
<dependency>
    <groupId>org.jboss.arquillian.extension</groupId>
    <artifactId>arquillian-warp-jsf</artifactId>
    <version>${version.warp}</version>
</dependency>
----

==== Use Servlet Protocol

In `arquillian.xml`:

----
<defaultProtocol type="Servlet 3.0"/>
----

==== Create a Test

The test needs to be annotated with `@WarpTest` and needs to be run on a client (`@RunAsClient`).

It needs to contain WAR deployment which will be testable:

----
@RunWith(Arquillian.class)
@WarpTest
@RunAsClient
public class BasicTest {
    
    @Deployment(testable = true)
    public static WebArchive deployment() {
       ...
    }

    @Test
    public void test() {
      // now we can use Warp
      Warp
        ...
    }
}
----

=== Warp API

The Warp requires two inputs from the user:

* what activity should be done in order to trigger a request
* リクエストのトリガーとなる activity はどのようなものか
* how the server processing should be inspected
* サーバ処理どうやって検証するか

That intuitively leads us to the simplest possible high-level API:

----
Warp
  .initiate(Activity)
  .inspect(Inspection);
----

Note: This is so called single-request execution API. In this API a first observed request is inspected.

The result of single-request execution API is an `Inspection` returned from a server:

----
CustomInspection result = 
  Warp
  .initiate(Activity)
  .inspect(CustomInspection);
----

=== Activity

The `Activity` is an manipulation with a client which leads to communication (emits a HTTP request). You are unlimited in tooling choices, but you should always use an URL provided by the Arquillian:

★あなたは常にArquillianはによって提供されたURLを使用する必要があります。
----
@ArquillianResource
URL contextPath;
----

So we can e.g. use simplest possible Warp activity:

----
Warp
  .initiate(new Activity() {
    InputStream connection = contextPath.getResourceAsStream();
    connection.open();
  }
----

You can use whatever tool you want here (e.g. HttpClient, Selenium WebDriver, etc.).

----
Warp
  .initiate(new Activity() {
    webdriver.navigate().to(contextPath.toString());
  }
----

=== Request Observers

Since HTTP clients can generally emit more than one request at a time, we may need to limit what will Warp react on.

HTTPクライアントは一般的に、一度に複数の要求を発することができるので、我々はWarpの反応がどうなるかを制限する必要があるかもしれません。

We can achieve that using Warp API extended for Request Observing:

----
Warp
  .initiate(Activity)
  .observe(Observer)
  .inspect(Inspection);
----

In case of HTTP requests, we want to use `HttpObserver` specifically. We can implement at own or use predefined fluent API for observer specification.

HTTPリクエストの場合には、特に`HttpObserver`使用します。自分で実装したり、observerの指定のために事前に定義された流暢なAPIを使用することができます。

==== Fluent API for HTTP Request Observing

In order to make observer definitions as accessible and readable as possible, there is fluent API for request observer specification:

----
import static ...request;
...
Warp
  .initiate(Activity)
  .observe(request().url().contains("index.html"))
  .inspect(Inspection);
----

=== Request Groups

An `Activity` inspected by `Warp` can lead not only to just one request, but also several paralell or sequential requests.

`Warp`によって検査された`Activity`はまた、ひとつのリクエストだけでなく、いくつかのparalellまたは順次リクエストにつながることができます。

In order to test multiple requests during one `Warp` execution, you can use Request Groups API:

ひとつの`Warp`の実行中に複数のリクエストをテストするためには、リクエストグループAPIを使用することができます

----
Warp
  .initiate(Activity)
  .group(id1)
    .observe(Observer)
    .inspect(Inspection...)
  .group(id2)
    .observe(Observer)
    .inspect(Inspection...)
  .execute();
----

Note that identifiers (`id1`, `id2`) are optional, they serve just a purpose of identification of a group in a result.

識別子（ID1、ID2）がオプションであることに注意してください、それらはただ結果のgroupの識別という目的を果たします。

Don't forget to use `.execute()` at the end of a Warp specification - it ends a specification and starts Warp execution process.

ワープ指示の最後に`.execute()` を使用することを忘れないでください、それは指示を終了し、ワープの実行プロセスを開始します。

Note that observers needs to be used for each of a group, since no request can belong to more than one group.

リクエストは複数のグループに属することができないので、observersは各々のgroupのために使用される必要があることに注意してください。

==== Multiple Requests per Group

The Request Group API can be used also for verification of multiple requests with same inspection:

リクエストグループAPIが、同じinspectionを持つ複数のリクエストの検証にも使用することができます。

----
Warp
  .initiate(Activity)
  .group()
    .count(2)
    .inspect(Inspection)
  .execute();
----

The definition above expresses that there are two similar requests expected which will be inspected by given Inspection.

定義は、上記のInspectionによって検査されると予想される２つの同様のリクエストがあることを表わしています。


==== Group Identifiers

For identification of a group, you can use arbitrary identifier (either primitive value or object with correctly implemented equivalence), so e.g.:

groupの識別のために、あなたは任意の識別子（プリミティブ値または正しく実装された等価であるオブジェクトのいずれか）を使用することができます。例：

----
   .group("group1")
   .group(1)
   .group(object);
   .group() // identifier is optional
----

==== Result of Warp Group Execution

As a result of non-trivial (not single-request) execution of a Warp is a `WarpResult`.

ワープの自明でない（非シングルリクエスト）を実行の結果がWarpResult`です。

----
WarpResult result = 
  Warp
  .initiate(Activity)
  .group(id)
    .inspect()
  .execute();
----

Once you have provided an identifier for a group, you can retrieve a `WarpGroup` result:

あなたはグループの識別子を指定すれば、`WarpGroup`結果を取得することができます。

----
WarpGroup group = result.getGroup(id);
----

The `WarpGroup` result can be used to:

* obtain an inspection returned from server
* サーバーから返されたinspectionを取得
* verify the state of responses
* レスポンスの状態を確認

=== Inspection

An initiated request can be inspected during its execution using

----
.inspect(new Inspection() {
  ...
})
----

An `Inspection` object 

* is serialized on a client and sent to a server
* クライアント上でシリアル化してサーバに送信される
* can bear a payload
* ペイロードを持てる
* can contain lifecycle hooks which triggers verification logic
* 検証ロジックのトリガーとなるライフサイクルフックを含めることができる
* can be enriched using dependency injection
* dependency injectionを使用することができる

=== Lifecycle Hooks

Once an inspection is transfered to a server VM, it can be used to assert a state.

inspectionがサーバVMに転送されると、それは状態をアサートするために使用することができます。

In order to define, when the inspection should execute its logic, one needs to use so called request lifecycle hooks.

inspectionがそのロジックを実行する必要がある場合、定義するために、リクエストライフサイクルのフックを使用する必要があります。

Most basic lifecycle hooks are:

|===
| `@BeforeServlet`  | executed before a servlet request enters servlet processing (in a servlet's filter chain)
| `@AfterServlet`   | executed after a servlet request leaves servlet processing (in a servlet's filter chain)
|===

The lifecycle hooks are used to invoke methods:

----
Warp
  .initiate(Activity)
  .inspect(new Inspection() {

    @BeforeServlet
    public void verifyRequest() {
      ...
    }
  });
----


There are also hooks specific for a each of the supported frameworks.

フレームワークにサポートされているそれぞれ具体的なフックがあります。

==== JavaServer Faces Lifecycle Hooks

JSF allows to hook into the request lifecycle:

|===
| @BeforePhase(Phase) | executed before a given JSF lifecycle phase is processed
| @AfterPhase(Phase)  | executed after a given JSF lifecycle phase is processed
|===

=== Dependency Injection

In order to test server-side state effectively, the `Inspection` can be enriched with any of the dependencies injectable by Arquillian:

効果的にサーバー側の状態をテストするために、`Inspection`はArquillianによるDIで強化することができます：

* `@Inject` for CDI beans
* `@EJB` for EJB beans
* `@ArquillianResource` for Arquillian Resources
* `@ManagedProperty("#{expression}")` for beans from Expression Language context (JSF)

The injection can be either class-level or method-level:

----
Warp
  .initiate(Activity)
  .inspect(new Inspection() {
    
    @ArquillianResource
    private HttpServletRequest request;

    @ManagedProperty("#{user.friends}")
    private Set<User> friends;

    @AfterPhase(INVOKE_APPLICATION)
    public void verifyRequest(@CurrentUser User user) {
      ...
    }
  });
----

As you can see in a sample above, CDI beans can be injected on method-level even though you don't specify `@Inject`.

上記のサンプルのとおり、`@Inject`指定しないにもかかわらず、CDI Beanはメソッドレベルでinjectすることができます。

==== Dependencies Specific to Servlets

Following resources can be injected using @ArquillianResource:

|===
| ServletRequest     | HttpServletRequest
| ServletResponse  | HttpServletResponse
|===

==== Dependencies Specific to JavaServer Faces

Following resources can be injected using @ArquillianResource:

|===
| FacesContext  | Application  | ExternalContext
| PartialViewContext  | ELContext  | ELResolver
| ExpressionFactory  | ViewHandler  | NavigationHandler
| ResourceHandler  | ExceptionHandler  | Flash
| RenderKit  | UIViewRoot  | StateManager
|===

=== Payload

Since an `Inspection` is a serializable object, it can contain a serializable payload which can be transfered with a request to a server, where it can be used as a base for a verification, for example:

`Inspection`はシリアル化可能なオブジェクトであるため、検証のためのベースとして使用することができ、サーバにリクエストを転送することができるシリアル化可能なペイロードを含めることができます。例えば：

* contain an object which will be use to initialize UI
* UIを初期化するために使用されるオブジェクトを含むことができる

Similarly, an `Inspection` processed on a server is serialized and sent to a client, thus it can contain an arbitrary information which can be used as a base for client verification logic, for example:

同様に、サーバ上で処理された`Inspection`がシリアル化されてクライアントに送信され、クライアント検証ロジックのベースとして使用することができる任意の情報を含めることができます。例えば：

* provide a client with the locale information of a server
* サーバーのロケール情報をクライアントに提供
* provide identifiers for UI elements in the generated page DOM
* 生成されたページのDOMのUI要素のための識別子を提供

Follows an example how one can use payload:

----
class CustomInspection {
  private SomePayload payload;
  ...
}

CustomInspection inspection = Warp
  .initiate(Activity)
  .inspect(new CustomInspection(payload));

SomePayload payload = inspection.getPayload();
----


=== Ability to Transfer an Inspection

The `Inspection` object has to follow just one contract in order to be transferable from a client to a server VM: all of its content has to be serializable.

`Inspection`オブジェクトは、サーバVMクライアントから転送可能にするためにひとつの制約に従います。その内容すべてがシリアル化可能である必要があります。

Note: Keep in mind that `Inspection` will be deployed to the server VM, so during its invocation, you can use only APIs available on server-side.

注：`Inspection`はサーバVMにデプロイされることに留意してください、その呼び出し中に、サーバー側で利用可能なAPIのみを使用することができます。

You can add desired APIs to the deployment and make them available to the server VM, but you should avoid exposing unwanted APIs to the server (e.g. API of client-side testing tools such as WebDriver).

デプロイしたいAPIを追加しサーバVMで利用できるようにしますが、サーバーに不要なAPIを公開することは避けてください（例えばwebdriverなどのクライアント側のテストツールのAPIなど）。

The execution of an inspection may lead into `ClassNotFoundException` or `LinkageError` if you won't stay compliant with this requirement.

inspectionの実行が`ClassNotFoundException`や`LinkageError` につながる可能性があります、もしこの要件に準拠しないなら。

==== Serializability of Anonymous/Inner Inspections

The anonymous and inner classes can be used as inspections thanks to transformation process which removes the binding from an non-static inner classes to top-level classes.

Keep in mind:

* you should not store an reference to an field in a top-level class
* the state of an inspection is serialized and thus its mutations on a server are not directly exposed to the client

== Debugging Warp

In order to debug Warp execution effectively, one needs to know few facts:

効果的にデバッグワープ実行するためには、知っている必要があります：

* Warp tries to provide as much as context during its failures as possible
** (if you are not provided with a context of a failure, let's report it)
* Warpは、可能な限り、その障害発生時にコンテキストを極力提供しようとする
** （あなたがfailureのコンテキストで提供されていない場合、それを報告してみましょう）
* the client-side execution can be debugged by usual approaches
* クライアント側の実行は、通常のアプローチによってデバッグすることができます
* the server-side execution can be debugged by usual approaches
* サーバー側の実行は、通常のアプローチによってデバッグすることができます
* Arquillian's debug output can reveal issues
* Arquillianはのデバッグ出力は、問題を明らかにすることができます

=== Arquillian Debugging Mode

In order to debug the tests effectively, one can reveal their internals by switching into an Arquillian debugging mode:

効果的にテストをデバッグするために、Arquillianをデバッグモードに切り替えることで、その内部を明らかにすることができます。

just pass `-Darquillian.debug=true` to the test and application server VM.

It will show event tree in a console which exposes you:

* what events are happening during test execution
* what requests/responses were registered by Warp
* what requests/responses were inspected by Warp
* what lifecycle hooks were hit

=== Debug Warp and WebDriver

In order to debug Warp's used together with WebDriver, one can use developer tools provided by browsers, such as:

* Chrome Developer Tools
* Firefox Developer Tools / Firebug
* IE Developer Tools
* Opera Dragonfly

and their ability to analyze Network traffic.

Refer to Graphene Reusable Session for best practices how to develop with WebDriver.

== Architecture

=== Warp Request Processing

In order to hook into client-to-server communication, Warp puts a HTTP proxy in between as illustrated on a image bellow.

TODO diagram

This proxy observes requests incoming from a client and then enhances a request with a payload required for a server inspection (processed reffered to as "piggy-backing on a request").

Once an enhanced request enters a server, it is blocked by a request filter and an inspection is registered into an Arquillian system. The Warp's filter then handles the processing to the traditional request processing.

During a requst processing lifecycle, the Warp listens for appropriate lifecycle hooks and as a response, it can execute arbitrary actions which inspects a state of the request context.

To help with a full-featured verification, a Warp's inspection process can leverage Arquillian's dependency injection system.

Once the request is processed by the server, leading into committing response, Warp can collect a result of inspection and enhance a built response to the client (again using piggy-backing method).

The Warp's proxy evaluates the response and either reports a failure (in case of server failure) or continues with execution of the test.
